config/routes.rb
Rails.application.routes.draw do
  get 'csv/import'
  post 'csv/import'
  get 'csv/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dataset.rb
class Dataset < ApplicationRecord
	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			# IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
			data = find_by(id: row["ID"]) || new
			# CSVからデータを取得し、設定する
			data.attributes = row.to_hash.slice(*updatable_attributes)
			# 保存する
			data.save
		end
	end

	# 更新を許可するカラムを定義
  def self.updatable_attributes
    ["Label", "House", "Year", "Month", "Temperature", "Daylight", "EnergyProduction", "created_at", "updated_at"]
	end
end

app/models/house_datum.rb
class HouseDatum < ApplicationRecord
	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			# IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
			data = find_by(id: row["ID"]) || new
			# CSVからデータを取得し、設定する
			data.attributes = row.to_hash.slice(*updatable_attributes)
			# 保存する
			data.save
		end
	end

	# 更新を許可するカラムを定義
  def self.updatable_attributes
    ["Firstname", "Lastname", "City", "num_of_people", "has_child", "created_at", "updated_at"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_controller.rb
require 'rails/all'
require 'csv'

class CsvController < ApplicationController
  def import
    if params[:file] != nil then
      if params[:file].original_filename == "dataset_50.csv" then
        Dataset.import(params[:file])
      elsif params[:file].original_filename == "house_data.csv" then
        HouseDatum.import(params[:file])
      end
    end
  end

  def index
    @house_data = HouseDatum.all
    @dataset = Dataset.all

    # sqlでデータを集計
    # City別エネルギー生産量
    sql = '
            SELECT
              City, count(*) as count
            FROM
              house_data
            GROUP BY
              City
          '
    city_house_count = ActiveRecord::Base.connection.select_all(sql).to_hash
    city_house_count.each do |data|
      @london_housese = data["count"] if data["City"] == "London"
      @cambrige_housese = data["count"] if data["City"] == "Cambridge"
      @oxford_housese = data["count"] if data["City"] == "Oxford"
    end

    sql = '
            SELECT
              City, SUM(EnergyProduction) as EnergyProduction
            FROM
              datasets
            INNER JOIN
              house_data
              ON datasets.House = house_data.ID
            GROUP BY
              City
          '
    city_energy = ActiveRecord::Base.connection.select_all(sql).to_hash

    city_energy.each do |data|
      @London = data["EnergyProduction"] if data["City"] == 'London'
      @Cambridge = data["EnergyProduction"] if data["City"] == 'Cambridge'
      @Oxford = data["EnergyProduction"] if data["City"] == 'Oxford'
    end

    # エネルギー生産量
    sql = '
            SELECT
              Year, Month, SUM(EnergyProduction) as EnergyProduction, City
            FROM
              datasets
            INNER JOIN
              house_data
              ON datasets.House = house_data.ID
            GROUP BY
              Year, Month, City
          '
    sql_result = ActiveRecord::Base.connection.select_all(sql).rows
    @lodon_year_energy = []
    @cambridge_year_energy = []
    @oxford_year_energy = []
    sql_result.each do |data|
      if data[3] == "London" then
        @lodon_year_energy.push [data[0], data[1], data[2]]
      elsif data[3] == "Cambridge" then
        @cambridge_year_energy.push [data[0], data[1], data[2]]
      elsif data[3] == "Oxford" then
        @oxford_year_energy.push [data[0], data[1], data[2]]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/views/csv/import.html.erb
<h1>Csv import</h1>
<p>
<div id = "button">
  <%= button_to 'csv data 画面へ', {:action => "index"}, {:method => :get} %>
</div>
</p>

<p>
<%= link_to "house_data.csv download", "https://csvsamples.s3.us-east-2.amazonaws.com/house_data.csv" %>
</p>

<p>
<%= link_to "dataset_50.csv download", "https://csvsamples.s3.us-east-2.amazonaws.com/dataset_50.csv" %>
</p>

<%= form_with url: csv_import_path do |form| %>
  <%= form.file_field :file %>
  <%= form.submit "インポート" %>
<% end %>

app/views/csv/index.html.erb
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">

  // google chartで図表作成
  // percentage of energy in cities

  google.load("visualization", "1", {packages:["corechart"]});

  google.setOnLoadCallback(drawChartSamplePie);
  function drawChartSamplePie() {
    var data = new google.visualization.DataTable();
    var data = google.visualization.arrayToDataTable([
      ['situation', 'number'],
      ['London\n(<%= @london_housese %>軒)', <%= @London %>],
      ['Cambridge\n(<%= @cambrige_housese %>軒)', <%= @Cambridge %>],
      ['Oxford\n(<%= @oxford_housese %>軒)', <%= @Oxford %>],
    ]);

    var options = {
      title: 'percentage of energy production in cities',
      is3D: true
    };

    var chart = new google.visualization.PieChart(document.getElementById('gct_sample_pie'));
    chart.draw(data, options);
  }


  // energy production
  function london() {
    google.setOnLoadCallback(
      function() {
        // rubyからのデータを処理する
        data_array = <%= @lodon_year_energy %>

        let data_for_chart = []
        data_array.forEach(function(item, index, array) {
          data_for_chart.push([new Date(item[0],item[1],01), item[2]]);
          return data_for_chart
        });
        // chart処理
        var data = new google.visualization.DataTable();
        data.addColumn('date', '');
        data.addColumn('number', 'energy');

        data.addRows(  data_for_chart );
        var options = {
          title: 'energy production',
          hAxis: {format: 'YYYY年MM月'}, // 表示フォーマットの指定
          legend: 'none'
        };
        var chart = new google.visualization.AreaChart(document.getElementById('gct_sample_area'));
        chart.draw(data, options);
      }
    );
  }

  function cambrige() {
    google.setOnLoadCallback(
      function() {
        // rubyからのデータを処理する
        data_array = <%= @cambridge_year_energy %>

        let data_for_chart = []
        data_array.forEach(function(item, index, array) {
          data_for_chart.push([new Date(item[0],item[1],01), item[2]]);
          return data_for_chart
        });
        // chart処理
        var data = new google.visualization.DataTable();
        data.addColumn('date', '');
        data.addColumn('number', 'energy');

        data.addRows(  data_for_chart );
        var options = {
          title: 'energy production',
          hAxis: {format: 'YYYY年MM月'}, // 表示フォーマットの指定
          legend: 'none'
        };
        var chart = new google.visualization.AreaChart(document.getElementById('gct_sample_area'));
        chart.draw(data, options);
      }
    );
  }

  function oxford() {
    google.setOnLoadCallback(
      function() {
        // rubyからのデータを処理する
        data_array = <%= @oxford_year_energy %>

        let data_for_chart = []
        data_array.forEach(function(item, index, array) {
          data_for_chart.push([new Date(item[0],item[1],01), item[2]]);
          return data_for_chart
        });
        // chart処理
        var data = new google.visualization.DataTable();
        data.addColumn('date', '');
        data.addColumn('number', 'energy');

        data.addRows(  data_for_chart );
        var options = {
          title: 'energy production',
          hAxis: {format: 'YYYY年MM月'}, // 表示フォーマットの指定
          legend: 'none'
        };
        var chart = new google.visualization.AreaChart(document.getElementById('gct_sample_area'));
        chart.draw(data, options);
      }
    );
  }

  window.onload = () => {
    london();
  }
</script>


<h1>Csv Data</h1>

<p>
<%= link_to "house_data.csv download", "https://csvsamples.s3.us-east-2.amazonaws.com/house_data.csv" %>
</p>

<p>
<%= link_to "dataset_50.csv download", "https://csvsamples.s3.us-east-2.amazonaws.com/dataset_50.csv" %>
</p>

<div id = "button">
  <%= button_to 'csv import 画面へ', {:action => "import"}, {:method => :get}%>
</div>


<h2>都市エネルギー生産量割合</h2>
<div id="gct_sample_pie" style="width: 400px;"></div>
<h2>都市別年間毎月エネルギー生産量</h2>
<%= form_with local: true do |form| %>
  <%= form.radio_button :city, :london, onClick: "london()", checked: 'checked' %>
  <%= form.label :city, "London", {value: :london, style: "display: inline-block;"} %>
  <%= form.radio_button :city, :cambrige, onClick: "cambrige()" %>
  <%= form.label :city, "Cambridge", {value: :cambrage, style: "display: inline-block;"} %>
  <%= form.radio_button :city, :oxford, onClick: "oxford()" %>
  <%= form.label :city, "Oxford", {value: :oxford, style: "display: inline-block;"} %>
<% end %>
<div id="gct_sample_area" style="width:80%; height:250pt" ></div>


<h1>house_data一覧</h1>

<table border='1'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>city</th>
      <th>num_of_people</th>
      <th>has_child</th>
      <th>created_at</th>
      <th>updated_at</th>
    </tr>
  </thead>

  <tbody>
    <% @house_data.each do |data| %>
      <tr>
        <td><%= data.ID %></td>
        <td><%= data.Firstname %></td>
        <td><%= data.Lastname %></td>
        <td><%= data.City %></td>
        <td><%= data.num_of_people %></td>
        <td><%= data.has_child %></td>
        <td><%= data.created_at %></td>
        <td><%= data.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>dataset_50一覧</h1>

<table border='1'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Label</th>
      <th>House</th>
      <th>Year</th>
      <th>Month</th>
      <th>Temperature</th>
      <th>Daylight</th>
      <th>EnergyProduction</th>
      <th>created_at</th>
      <th>updated_at</th>
    </tr>
  </thead>

  <tbody>
    <% @dataset.each do |data| %>
      <tr>
        <td><%= data.ID %></td>
        <td><%= data.Label %></td>
        <td><%= data.House %></td>
        <td><%= data.Year %></td>
        <td><%= data.Month %></td>
        <td><%= data.Temperature %></td>
        <td><%= data.Daylight %></td>
        <td><%= data.EnergyProduction %></td>
        <td><%= data.created_at %></td>
        <td><%= data.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec2RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>